# Generated by Django 6.1.1 on 2026-09-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Сообщение с формы обратной связи',
                'verbose_name_plural': 'Сообщения с формы обратной связи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('content_ru', models.TextField(help_text='Поддерживается базовый HTML.', verbose_name='Содержимое (RU)')),
                ('content_en', models.TextField(help_text='Basic HTML is supported.', verbose_name='Content (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница документации',
                'verbose_name_plural': 'Документация',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, help_text='Emoji or short symbol shown next to the title, e.g. 🎛️', max_length=10)),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (RU)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Возможность',
                'verbose_name_plural': 'Возможности',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/', verbose_name='Изображение')),
                ('caption_ru', models.CharField(blank=True, max_length=200, verbose_name='Подпись (RU)')),
                ('caption_en', models.CharField(blank=True, max_length=200, verbose_name='Caption (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Скриншот',
                'verbose_name_plural': 'Скриншоты',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_ru', models.TextField(blank=True, verbose_name='О проекте (RU)')),
                ('about_en', models.TextField(blank=True, verbose_name='About (EN)')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для связи')),
                ('github_url', models.URLField(blank=True, verbose_name='Ссылка на GitHub')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Информация о проекте',
                'verbose_name_plural': 'Информация о проекте',
            },
        ),
    ]
