# Generated by Django 6.1.1 on 2026-09-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name: knob, sliders, code, sync, wave, layers, cursor, cpu, editor, package, plug, check. Any other text (e.g. an emoji) is shown as is.', max_length=10),
        ),
    ]
